root_dir: /data0/zhr21/GitHub_repo/Bird-MAE
work_dir: ${hydra:runtime.cwd}

output_dir: ${hydra:runtime.output_dir}

dataset_dir: ${paths.root_dir}/data/${data.dataset.name}
log_dir: ${paths.root_dir}/logs/
model_dir: ${paths.log_dir}/model_checkpoints/
background_dir: /scratch/birdset/background/wav/

